# 纯 PXE ProxyDHCP —— 不分配IP，只做引导
port=0
interface=ens33
log-queries
log-dhcp

# Proxy 模式
dhcp-range=172.16.143.0,proxy

# iPXE 
dhcp-option=66,172.16.143.3
dhcp-option=67,undionly.kpxe
#dhcp-option=176,http://172.16.143.3:8080/menu.ipxe

dhcp-no-override
#dhcp-authoritative

# BIOS
pxe-service=0,"Bootimus BIOS",undionly.kpxe,172.16.143.3

# UEFI
pxe-service=7,"Bootimus UEFI",ipxe.efi,172.16.143.3
pxe-service=9,"Bootimus UEFI",ipxe.efi,172.16.143.3
