port=0
interface=ens33	#替换网卡名，该参数应该可删除，未测试
log-queries
log-dhcp

dhcp-range=172.16.143.0,proxy	#替换ip网段

dhcp-option=66,172.16.143.3	#替换你的ip，最好静态ip
dhcp-option=67,undionly.kpxe

dhcp-no-override

# BIOS
pxe-service=0,"Bootimus BIOS",undionly.kpxe,172.16.143.3	#替换你的ip

# UEFI
pxe-service=7,"Bootimus UEFI",ipxe.efi,172.16.143.3	#替换你的ip
pxe-service=9,"Bootimus UEFI",ipxe.efi,172.16.143.3	#替换你的ip
